#!/usr/bin/env bash
#
# Deploy script for Sakina.
#
# The app builds to plain static HTML (out/index.html and friends), so it can
# be dropped onto any web host: cPanel/DomaiNesia, Netlify, Cloudflare Pages,
# nginx, S3. There is no Node process to keep alive and no database.
#
# Usage:
#   ./deploy.sh                 build + package into a zip you can upload
#   ./deploy.sh --rsync         build + rsync straight to a live directory
#   ./deploy.sh --local         build + serve locally to check before shipping
#
# Configure the two variables below before the first --rsync run.

set -euo pipefail

# ─── Configuration ──────────────────────────────────────────────────────────

# Where the built site should land on the server (used by --rsync).
# For DomaiNesia/cPanel this is usually ~/public_html or a subfolder of it.
LIVE_DIR="${LIVE_DIR:-/home/USER/public_html}"

# SSH target for --rsync. Leave empty to rsync to a local path instead.
SSH_HOST="${SSH_HOST:-}"

# Set when serving from a subdirectory, e.g. BASE_PATH=/quran for
# example.com/quran. Leave empty when serving from the domain root.
BASE_PATH="${BASE_PATH:-}"

# ─── Internals ──────────────────────────────────────────────────────────────

BUILD_DIR="out"
ARTIFACT="sakina-$(date +%Y%m%d-%H%M).zip"
MODE="${1:---zip}"

log()  { printf '\033[1;36m▸ %s\033[0m\n' "$1"; }
ok()   { printf '\033[1;32m✓ %s\033[0m\n' "$1"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$1"; }
die()  { printf '\033[1;31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

# ─── 1. Pre-flight ──────────────────────────────────────────────────────────

command -v node >/dev/null || die "Node.js is not installed."
command -v pnpm >/dev/null || die "pnpm is not installed. Run: npm i -g pnpm"

NODE_MAJOR="$(node -v | sed 's/^v\([0-9]*\).*/\1/')"
[ "$NODE_MAJOR" -ge 20 ] || die "Node 20+ required (found $(node -v))."

log "Installing dependencies"
pnpm install --frozen-lockfile

# ─── 2. Quality gates ───────────────────────────────────────────────────────
#
# A broken build is far cheaper to catch here than on the live site, so the
# deploy refuses to continue if lint, architecture rules or tests fail.

log "Running checks (lint, architecture, tests)"
pnpm verify || die "Checks failed. Fix them before deploying."
ok "Checks passed"

# ─── 3. Build ───────────────────────────────────────────────────────────────
#
# The build fetches the reciter catalogue to pre-render one page per reciter,
# so it needs network access. If the API is unreachable it falls back to a
# built-in list of well-known reciters rather than failing the deploy.

log "Building static site"
rm -rf "$BUILD_DIR"
BUILD_TARGET=static BASE_PATH="$BASE_PATH" pnpm build

[ -f "$BUILD_DIR/index.html" ] || die "Build produced no $BUILD_DIR/index.html"

PAGE_COUNT="$(find "$BUILD_DIR" -name 'index.html' | wc -l | tr -d ' ')"
BUILD_SIZE="$(du -sh "$BUILD_DIR" | cut -f1)"
ok "Built $PAGE_COUNT pages ($BUILD_SIZE)"

# ─── 4. Apache config ───────────────────────────────────────────────────────
#
# Only used by Apache hosts (cPanel/DomaiNesia); harmless everywhere else.
# Static export cannot emit HTTP headers itself, so caching and compression
# rules have to live here.

log "Writing .htaccess"
cat > "$BUILD_DIR/.htaccess" <<'HTACCESS'
# Generated by deploy.sh — do not edit by hand.

# Clean URLs: /reciters/name/ is served from that folder's index.html.
DirectoryIndex index.html
Options -Indexes

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain
  AddOutputFilterByType DEFLATE application/javascript application/json
  AddOutputFilterByType DEFLATE image/svg+xml
</IfModule>

<IfModule mod_expires.c>
  ExpiresActive On

  # Hashed build assets never change under the same name.
  <FilesMatch "\.(js|css|woff2)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>

  # HTML must revalidate, or users get yesterday's app after a deploy.
  <FilesMatch "\.html$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>

  ExpiresByType image/webp "access plus 1 year"
  ExpiresByType image/avif "access plus 1 year"
  ExpiresByType image/svg+xml "access plus 1 year"
</IfModule>

<IfModule mod_headers.c>
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

ErrorDocument 404 /404.html
HTACCESS
ok ".htaccess written"

# ─── 5. Ship ────────────────────────────────────────────────────────────────

case "$MODE" in
  --local)
    log "Serving $BUILD_DIR at http://localhost:8080 (Ctrl+C to stop)"
    command -v npx >/dev/null || die "npx not found."
    npx --yes serve "$BUILD_DIR" -l 8080
    ;;

  --rsync)
    command -v rsync >/dev/null || die "rsync is not installed."

    # rsync --delete wipes anything already in the target, so refuse the
    # obviously catastrophic paths outright.
    case "$LIVE_DIR" in
      ""|"/"|"$HOME"|"/home"|"/root")
        die "LIVE_DIR ('$LIVE_DIR') looks unsafe. Set it to a real web root." ;;
    esac
    if [ "$LIVE_DIR" = "/home/USER/public_html" ]; then
      die "LIVE_DIR is still the placeholder. Edit it at the top of this script."
    fi

    TARGET="$LIVE_DIR"
    [ -n "$SSH_HOST" ] && TARGET="$SSH_HOST:$LIVE_DIR"

    warn "About to mirror $BUILD_DIR/ → $TARGET (existing files there are deleted)"
    read -r -p "Continue? [y/N] " reply
    [ "$reply" = "y" ] || [ "$reply" = "Y" ] || die "Aborted."

    log "Syncing"
    rsync -avz --delete \
      --exclude '.DS_Store' \
      "$BUILD_DIR/" "$TARGET/"

    ok "Deployed to $TARGET"
    ;;

  --zip|*)
    command -v zip >/dev/null || die "zip is not installed."
    log "Packaging"
    rm -f "$ARTIFACT"
    (cd "$BUILD_DIR" && zip -qr "../$ARTIFACT" . -x '.DS_Store')
    ok "Created $ARTIFACT ($(du -h "$ARTIFACT" | cut -f1))"
    echo
    echo "Upload it and extract into your web root (e.g. public_html)."
    echo "In cPanel: File Manager → public_html → Upload → Extract."
    ;;
esac

echo
ok "Done."
