/**
 * Static surah reference data — numbers, names, ayah counts, revelation place.
 *
 * This is factual catalogue metadata, not scripture text, and it never
 * changes. Bundling it means the app renders a full, browsable catalogue on
 * first paint with no network call, which is what makes the offline-first
 * promise in the PRD actually hold.
 */

export interface SurahRecord {
  readonly number: number;
  readonly nameLatin: string;
  readonly nameArabic: string;
  readonly nameTranslation: string;
  readonly ayahCount: number;
  readonly revelationPlace: "meccan" | "medinan";
}

type Row = [number, string, string, string, number, 0 | 1];

// [number, latin, arabic, translation, ayahs, 0=meccan 1=medinan]
const ROWS: Row[] = [
  [1, "Al-Fatihah", "الفاتحة", "The Opening", 7, 0],
  [2, "Al-Baqarah", "البقرة", "The Cow", 286, 1],
  [3, "Ali 'Imran", "آل عمران", "Family of Imran", 200, 1],
  [4, "An-Nisa", "النساء", "The Women", 176, 1],
  [5, "Al-Ma'idah", "المائدة", "The Table Spread", 120, 1],
  [6, "Al-An'am", "الأنعام", "The Cattle", 165, 0],
  [7, "Al-A'raf", "الأعراف", "The Heights", 206, 0],
  [8, "Al-Anfal", "الأنفال", "The Spoils of War", 75, 1],
  [9, "At-Tawbah", "التوبة", "The Repentance", 129, 1],
  [10, "Yunus", "يونس", "Jonah", 109, 0],
  [11, "Hud", "هود", "Hud", 123, 0],
  [12, "Yusuf", "يوسف", "Joseph", 111, 0],
  [13, "Ar-Ra'd", "الرعد", "The Thunder", 43, 1],
  [14, "Ibrahim", "ابراهيم", "Abraham", 52, 0],
  [15, "Al-Hijr", "الحجر", "The Rocky Tract", 99, 0],
  [16, "An-Nahl", "النحل", "The Bee", 128, 0],
  [17, "Al-Isra", "الإسراء", "The Night Journey", 111, 0],
  [18, "Al-Kahf", "الكهف", "The Cave", 110, 0],
  [19, "Maryam", "مريم", "Mary", 98, 0],
  [20, "Taha", "طه", "Ta-Ha", 135, 0],
  [21, "Al-Anbya", "الأنبياء", "The Prophets", 112, 0],
  [22, "Al-Hajj", "الحج", "The Pilgrimage", 78, 1],
  [23, "Al-Mu'minun", "المؤمنون", "The Believers", 118, 0],
  [24, "An-Nur", "النور", "The Light", 64, 1],
  [25, "Al-Furqan", "الفرقان", "The Criterion", 77, 0],
  [26, "Ash-Shu'ara", "الشعراء", "The Poets", 227, 0],
  [27, "An-Naml", "النمل", "The Ant", 93, 0],
  [28, "Al-Qasas", "القصص", "The Stories", 88, 0],
  [29, "Al-'Ankabut", "العنكبوت", "The Spider", 69, 0],
  [30, "Ar-Rum", "الروم", "The Romans", 60, 0],
  [31, "Luqman", "لقمان", "Luqman", 34, 0],
  [32, "As-Sajdah", "السجدة", "The Prostration", 30, 0],
  [33, "Al-Ahzab", "الأحزاب", "The Combined Forces", 73, 1],
  [34, "Saba", "سبإ", "Sheba", 54, 0],
  [35, "Fatir", "فاطر", "Originator", 45, 0],
  [36, "Ya-Sin", "يس", "Ya Sin", 83, 0],
  [37, "As-Saffat", "الصافات", "Those Who Set The Ranks", 182, 0],
  [38, "Sad", "ص", "The Letter Sad", 88, 0],
  [39, "Az-Zumar", "الزمر", "The Troops", 75, 0],
  [40, "Ghafir", "غافر", "The Forgiver", 85, 0],
  [41, "Fussilat", "فصلت", "Explained In Detail", 54, 0],
  [42, "Ash-Shuraa", "الشورى", "The Consultation", 53, 0],
  [43, "Az-Zukhruf", "الزخرف", "The Ornaments of Gold", 89, 0],
  [44, "Ad-Dukhan", "الدخان", "The Smoke", 59, 0],
  [45, "Al-Jathiyah", "الجاثية", "The Crouching", 37, 0],
  [46, "Al-Ahqaf", "الأحقاف", "The Wind-Curved Sandhills", 35, 0],
  [47, "Muhammad", "محمد", "Muhammad", 38, 1],
  [48, "Al-Fath", "الفتح", "The Victory", 29, 1],
  [49, "Al-Hujurat", "الحجرات", "The Rooms", 18, 1],
  [50, "Qaf", "ق", "The Letter Qaf", 45, 0],
  [51, "Adh-Dhariyat", "الذاريات", "The Winnowing Winds", 60, 0],
  [52, "At-Tur", "الطور", "The Mount", 49, 0],
  [53, "An-Najm", "النجم", "The Star", 62, 0],
  [54, "Al-Qamar", "القمر", "The Moon", 55, 0],
  [55, "Ar-Rahman", "الرحمن", "The Beneficent", 78, 1],
  [56, "Al-Waqi'ah", "الواقعة", "The Inevitable", 96, 0],
  [57, "Al-Hadid", "الحديد", "The Iron", 29, 1],
  [58, "Al-Mujadila", "المجادلة", "The Pleading Woman", 22, 1],
  [59, "Al-Hashr", "الحشر", "The Exile", 24, 1],
  [60, "Al-Mumtahanah", "الممتحنة", "She That Is To Be Examined", 13, 1],
  [61, "As-Saf", "الصف", "The Ranks", 14, 1],
  [62, "Al-Jumu'ah", "الجمعة", "The Congregation, Friday", 11, 1],
  [63, "Al-Munafiqun", "المنافقون", "The Hypocrites", 11, 1],
  [64, "At-Taghabun", "التغابن", "The Mutual Disillusion", 18, 1],
  [65, "At-Talaq", "الطلاق", "The Divorce", 12, 1],
  [66, "At-Tahrim", "التحريم", "The Prohibition", 12, 1],
  [67, "Al-Mulk", "الملك", "The Sovereignty", 30, 0],
  [68, "Al-Qalam", "القلم", "The Pen", 52, 0],
  [69, "Al-Haqqah", "الحاقة", "The Reality", 52, 0],
  [70, "Al-Ma'arij", "المعارج", "The Ascending Stairways", 44, 0],
  [71, "Nuh", "نوح", "Noah", 28, 0],
  [72, "Al-Jinn", "الجن", "The Jinn", 28, 0],
  [73, "Al-Muzzammil", "المزمل", "The Enshrouded One", 20, 0],
  [74, "Al-Muddaththir", "المدثر", "The Cloaked One", 56, 0],
  [75, "Al-Qiyamah", "القيامة", "The Resurrection", 40, 0],
  [76, "Al-Insan", "الانسان", "The Man", 31, 1],
  [77, "Al-Mursalat", "المرسلات", "The Emissaries", 50, 0],
  [78, "An-Naba", "النبأ", "The Tidings", 40, 0],
  [79, "An-Nazi'at", "النازعات", "Those Who Drag Forth", 46, 0],
  [80, "'Abasa", "عبس", "He Frowned", 42, 0],
  [81, "At-Takwir", "التكوير", "The Overthrowing", 29, 0],
  [82, "Al-Infitar", "الإنفطار", "The Cleaving", 19, 0],
  [83, "Al-Mutaffifin", "المطففين", "The Defrauding", 36, 0],
  [84, "Al-Inshiqaq", "الإنشقاق", "The Sundering", 25, 0],
  [85, "Al-Buruj", "البروج", "The Mansions of the Stars", 22, 0],
  [86, "At-Tariq", "الطارق", "The Nightcomer", 17, 0],
  [87, "Al-A'la", "الأعلى", "The Most High", 19, 0],
  [88, "Al-Ghashiyah", "الغاشية", "The Overwhelming", 26, 0],
  [89, "Al-Fajr", "الفجر", "The Dawn", 30, 0],
  [90, "Al-Balad", "البلد", "The City", 20, 0],
  [91, "Ash-Shams", "الشمس", "The Sun", 15, 0],
  [92, "Al-Layl", "الليل", "The Night", 21, 0],
  [93, "Ad-Duhaa", "الضحى", "The Morning Hours", 11, 0],
  [94, "Ash-Sharh", "الشرح", "The Relief", 8, 0],
  [95, "At-Tin", "التين", "The Fig", 8, 0],
  [96, "Al-'Alaq", "العلق", "The Clot", 19, 0],
  [97, "Al-Qadr", "القدر", "The Power", 5, 0],
  [98, "Al-Bayyinah", "البينة", "The Clear Proof", 8, 1],
  [99, "Az-Zalzalah", "الزلزلة", "The Earthquake", 8, 1],
  [100, "Al-'Adiyat", "العاديات", "The Courser", 11, 0],
  [101, "Al-Qari'ah", "القارعة", "The Calamity", 11, 0],
  [102, "At-Takathur", "التكاثر", "The Rivalry in World Increase", 8, 0],
  [103, "Al-'Asr", "العصر", "The Declining Day", 3, 0],
  [104, "Al-Humazah", "الهمزة", "The Traducer", 9, 0],
  [105, "Al-Fil", "الفيل", "The Elephant", 5, 0],
  [106, "Quraysh", "قريش", "Quraysh", 4, 0],
  [107, "Al-Ma'un", "الماعون", "The Small Kindnesses", 7, 0],
  [108, "Al-Kawthar", "الكوثر", "The Abundance", 3, 0],
  [109, "Al-Kafirun", "الكافرون", "The Disbelievers", 6, 0],
  [110, "An-Nasr", "النصر", "The Divine Support", 3, 1],
  [111, "Al-Masad", "المسد", "The Palm Fibre", 5, 0],
  [112, "Al-Ikhlas", "الإخلاص", "The Sincerity", 4, 0],
  [113, "Al-Falaq", "الفلق", "The Daybreak", 5, 0],
  [114, "An-Nas", "الناس", "Mankind", 6, 0],
];

export const SURAH_DATA: readonly SurahRecord[] = ROWS.map(
  ([number, nameLatin, nameArabic, nameTranslation, ayahCount, place]) => ({
    number,
    nameLatin,
    nameArabic,
    nameTranslation,
    ayahCount,
    revelationPlace: place === 0 ? "meccan" : "medinan",
  }),
);

/** Indonesian translations of the surah names, for the id locale. */
export const SURAH_NAME_ID: Readonly<Record<number, string>> = {
  1: "Pembukaan",
  2: "Sapi Betina",
  3: "Keluarga Imran",
  4: "Wanita",
  5: "Hidangan",
  6: "Binatang Ternak",
  7: "Tempat Tertinggi",
  8: "Rampasan Perang",
  9: "Pengampunan",
  10: "Nabi Yunus",
  11: "Nabi Hud",
  12: "Nabi Yusuf",
  13: "Guruh",
  14: "Nabi Ibrahim",
  15: "Gunung Al Hijr",
  16: "Lebah",
  17: "Perjalanan Malam",
  18: "Gua",
  19: "Maryam",
  20: "Taha",
  21: "Para Nabi",
  22: "Haji",
  23: "Orang-orang Mukmin",
  24: "Cahaya",
  25: "Pembeda",
  26: "Penyair",
  27: "Semut",
  28: "Kisah-kisah",
  29: "Laba-laba",
  30: "Bangsa Romawi",
  31: "Luqman",
  32: "Sajdah",
  33: "Golongan yang Bersekutu",
  34: "Kaum Saba",
  35: "Pencipta",
  36: "Yasin",
  37: "Barisan-barisan",
  38: "Sad",
  39: "Rombongan",
  40: "Yang Mengampuni",
  41: "Yang Dijelaskan",
  42: "Musyawarah",
  43: "Perhiasan",
  44: "Kabut",
  45: "Yang Berlutut",
  46: "Bukit Pasir",
  47: "Nabi Muhammad",
  48: "Kemenangan",
  49: "Kamar-kamar",
  50: "Qaf",
  51: "Angin yang Menerbangkan",
  52: "Bukit",
  53: "Bintang",
  54: "Bulan",
  55: "Yang Maha Pemurah",
  56: "Hari Kiamat",
  57: "Besi",
  58: "Wanita yang Mengajukan Gugatan",
  59: "Pengusiran",
  60: "Wanita yang Diuji",
  61: "Satu Barisan",
  62: "Hari Jumat",
  63: "Orang-orang Munafik",
  64: "Hari Ditampakkan Kesalahan",
  65: "Talak",
  66: "Pengharaman",
  67: "Kerajaan",
  68: "Pena",
  69: "Hari Kiamat",
  70: "Tempat Naik",
  71: "Nabi Nuh",
  72: "Jin",
  73: "Orang yang Berselimut",
  74: "Orang yang Berkemul",
  75: "Kiamat",
  76: "Manusia",
  77: "Malaikat yang Diutus",
  78: "Berita Besar",
  79: "Malaikat yang Mencabut",
  80: "Ia Bermuka Masam",
  81: "Menggulung",
  82: "Terbelah",
  83: "Orang-orang yang Curang",
  84: "Terbelah",
  85: "Gugusan Bintang",
  86: "Yang Datang di Malam Hari",
  87: "Yang Paling Tinggi",
  88: "Hari Pembalasan",
  89: "Fajar",
  90: "Negeri",
  91: "Matahari",
  92: "Malam",
  93: "Waktu Duha",
  94: "Melapangkan",
  95: "Buah Tin",
  96: "Segumpal Darah",
  97: "Kemuliaan",
  98: "Bukti Nyata",
  99: "Kegoncangan",
  100: "Kuda Perang",
  101: "Hari Kiamat",
  102: "Bermegah-megahan",
  103: "Masa",
  104: "Pengumpat",
  105: "Gajah",
  106: "Suku Quraisy",
  107: "Barang yang Berguna",
  108: "Nikmat yang Banyak",
  109: "Orang-orang Kafir",
  110: "Pertolongan",
  111: "Sabut",
  112: "Ikhlas",
  113: "Waktu Subuh",
  114: "Manusia",
};
