import { Entity } from "../shared/entity";

/**
 * Licence is a first-class field, not a comment. Every ambient asset must
 * be CC0 or public domain — the catalogue is validated against this at build
 * time so a wrongly-licensed clip cannot ship.
 */
export const AmbientLicense = {
  /** Generated by our own synthesis code — no third-party rights involved. */
  Original: "original",
  CC0: "cc0",
  PublicDomain: "public-domain",
} as const;

export type AmbientLicense =
  (typeof AmbientLicense)[keyof typeof AmbientLicense];

export interface AmbientSoundProps {
  readonly id: string;
  readonly name: string;
  /** Lucide icon name rendered in the picker grid. */
  readonly icon: string;
  readonly audioUrl: string;
  /** Landscape shown behind the full-screen player when this sound is active. */
  readonly imageUrl: string | null;
  readonly license: AmbientLicense;
  readonly attribution: string;
  readonly sourceUrl: string;
}

export class AmbientSound extends Entity<string> {
  /** Sentinel entry rendered as "No sounds" in the picker. */
  static readonly NONE_ID = "none";

  private constructor(private readonly props: AmbientSoundProps) {
    super(props.id);
  }

  static create(props: AmbientSoundProps): AmbientSound {
    return new AmbientSound(props);
  }

  static none(): AmbientSound {
    return new AmbientSound({
      id: AmbientSound.NONE_ID,
      name: "No sounds",
      icon: "Minus",
      audioUrl: "",
      imageUrl: null,
      license: AmbientLicense.CC0,
      attribution: "—",
      sourceUrl: "",
    });
  }

  get name(): string {
    return this.props.name;
  }

  get icon(): string {
    return this.props.icon;
  }

  get audioUrl(): string {
    return this.props.audioUrl;
  }

  get imageUrl(): string | null {
    return this.props.imageUrl;
  }

  get license(): AmbientLicense {
    return this.props.license;
  }

  get attribution(): string {
    return this.props.attribution;
  }

  get sourceUrl(): string {
    return this.props.sourceUrl;
  }

  get isNone(): boolean {
    return this.props.id === AmbientSound.NONE_ID;
  }

  matches(query: string): boolean {
    const q = query.trim().toLowerCase();
    return q.length === 0 || this.props.name.toLowerCase().includes(q);
  }
}
