import credits from "@/infrastructure/content/scenery-credits.json";

/**
 * Attribution for the player backdrop photography.
 *
 * The JSON is generated by `scripts/fetch-scenery.mjs`, so it always matches
 * the images that actually shipped. Route files reach it through here rather
 * than importing infrastructure directly, which the architecture rules forbid.
 */
export interface SceneryCredit {
  readonly title: string;
  readonly author: string;
  readonly licence: string;
  readonly source: string;
}

export const SCENERY_CREDITS: Readonly<Record<string, SceneryCredit>> = credits;

/** Sorted for a stable render order on the credits screen. */
export const SCENERY_CREDIT_ENTRIES: readonly (readonly [
  string,
  SceneryCredit,
])[] = Object.entries(SCENERY_CREDITS).sort(([a], [b]) => a.localeCompare(b));
